version: '3.8'

services:
  nlw-expert-api:
    container_name: nlw-expert-api
    build: .
    tty: true # docker run -t
    stdin_open: true # docker run -i
    restart: always
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/polls?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD="password"
      - origin="*"
      - HOST=0.0.0.0
      - PORT=3333
    networks:
      - databases-network

networks:
  databases-network:
    external: true