version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - polls_pg_data:/bitnami/postgresql
    networks:
      - databases-network

  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=password
    ports:
      - '6379:6379'
    volumes:
      - polls_redis_data:/bitnami/redis/data
    networks:
      - databases-network

volumes:
  polls_pg_data:
  polls_redis_data:

networks:
  databases-network:
    external: true