version: '3.8'

services:
  nlw-expert-api:
    container_name: nlw-expert-api
    build: .
    tty: true # docker run -t
    stdin_open: true # docker run -i
    restart: always
    ports:
      - ${APP_PUBLIC_PORT}:${APP_PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - origin=${CORS_ORIGIN}
      - HOST=${APP_HOST}
      - PORT=${APP_PORT}
    networks:
      - databases-network

networks:
  databases-network:
    external: true