name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy with SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
          DATABASE_URL: ${{ secrets.PG_DATABASE_URL }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          APP_HOST: ${{ vars.APP_HOST }}
          APP_PORT: ${{ vars.APP_PORT }}
          APP_PUBLIC_PORT: ${{ vars.APP_PUBLIC_PORT }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        envs: DATABASE_URL,REDIS_HOST,REDIS_PASSWORD,REDIS_PORT,CORS_ORIGIN,APP_HOST,APP_PORT,APP_PUBLIC_PORT
        allenvs: true
        script: |
          cd /home/deploy/nlw-expert-polls
          git pull origin master
          git status
          npm ci
          npx prisma migrate deploy
          docker compose up -d --build