name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy with SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_DB: ${{ secrets.PG_DB }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_PORT: ${{ secrets.APP_PORT }}
          APP_PUBLIC_PORT: ${{ secrets.APP_PUBLIC_PORT }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        envs: PG_HOST,PG_USER,PG_PASSWORD,PG_PORT,PG_DB,REDIS_HOST,REDIS_PASSWORD,REDIS_PORT,CORS_ORIGIN,APP_HOST,APP_PORT,APP_PUBLIC_PORT
        script: |
          cd /home/deploy/nlw-expert-polls
          git pull origin master
          git status
          npm ci
          docker compose up -d --build